### ISSUE TITLE
Add (TARGET_)REF_EPOCH, PMRA, PMDEC to fiberassign table

### ISSUE THREAD

**Issue by stephjuneau** [desihub/specprod-db#5]
As per 2023-05-30 data telecon, add the REF_EPOCH to the TARGET_RA, TARGET_DEC columns (possibly renaming to TARGET_REF_EPOCH) and also the proper motion columns: PMRA, PMDEC.

Question (Cc @sbailey ): do we need to also propagate the _IVAR on the coordinates and proper motion or are we happy for those to be in the photometry table (not sure if they were updated during the fiberassign step with proper motion calculations for CMX & SV1 -- @araichoor )?

**Comment by weaverba137** [comment]
For reference: RA, DEC inverse variances are *not* in the fiberassign tables that are loaded into the database, so this would potentially be significantly more complicated to add.

**Comment by araichoor** [comment]
the {RA,DEC}_IVAR columns were not touched in fiberassign.

also: if PLATE_{RA,DEC} are in the fiberassign table, we d also want to propagate PLATE_REF_EPOCH (and, as said, so far those PLATE_{RA,DEC,REF_EPOCH} are just pure copy of the TARGET_RA,TARGET_DEC,REF_EPOCH).

**Comment by stephjuneau** [comment]
@araichoor do we need the PLATE_* columns if they don't provide us with new information not already in TARGET_* columns?

**Comment by araichoor** [comment]
so far, those are simply copies of the TARGET_* columns; so for fuji and iron, they don t add any new information.
I think we can get rid of those.
I list below the infos I m aware of about those, for others to make their judgement.

their purpose was to anticipate the case where e.g. we d apply some chromatic correction on the fiber position (depending on the position on the focal plane, with using I think LAMBDA_REF); but we never implemented that; and I m not sure we will change things at this point in the survey..

besides, I think that those are the columns used by platemaker; but this code is not easily accessible, and I m not sure anyone would need to rerun that.

**Comment by stephjuneau** [comment]
As a reference, the zpix files have TARGET_RA, TARGET_DEC, REF_EPOCH, PMRA, PMDEC but do *not* have the IVAR columns. So we could adopt the same solution for both `fiberassign` and `zpix` (but for `zpix` after the data are already in the database and just by adding columns. I'll make a separate issue as it'd be a different process).

Edit: Based on what Anand wrote above, I am in favor of dropping PLATE_RA, PLATE_DEC (rather than keeping them and adding PLATE_REF_EPOCH).

**Comment by weaverba137** [comment]
Closed by #4
